# Generated by Django 5.0 on 2024-03-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='phone',
            new_name='username',
        ),
    ]
