# Generated by Django 5.0 on 2024-03-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_phone_otp_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='username',
            new_name='phone',
        ),
    ]
