# Generated by Django 5.0 on 2024-03-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کد های تایید'},
        ),
    ]
