# Generated by Django 5.0 on 2024-03-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_product_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
    ]
